name: my_env
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
channels:
  - conda-forge
dependencies:
  - python=3.7.9
  - rdkit
  - pip
  - pip:
      - streamlit==0.75.0
      - pandas==1.1.3
      - mols2grid
      - click==8
